import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ModalProvider } from "@/commons/providers/modal/modal.provider";
import { NextThemesProvider } from "@/commons/providers/next-themes/next-themes.provider";
import { ReactQueryProvider } from "@/commons/providers/react-query/react-query.provider";
import { AuthProvider } from "@/commons/providers/auth/auth.provider";
import { AuthGuard } from "@/commons/providers/auth/auth.guard";
import Layout from "@/commons/layout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ReactQueryProvider>
            <NextThemesProvider>
              <ModalProvider>
                <AuthGuard>
                  <Layout>{children}</Layout>
                </AuthGuard>
              </ModalProvider>
            </NextThemesProvider>
          </ReactQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
